
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EntityFrameworkPlusTest
{

using System;
    using System.Collections.Generic;
    
public partial class CustomerPackagesHistory
{

    public int ID { get; set; }

    public int CustomerID { get; set; }

    public int PackageID { get; set; }

    public int PackageQty { get; set; }

    public System.DateTime OperationDate { get; set; }

}

}
