

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EntityFrameworkPlusTest
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class EntityFrameworkPlusEntities : DbContext
{
    public EntityFrameworkPlusEntities()
        : base("name=EntityFrameworkPlusEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<CustomerPackagesHistory> CustomerPackagesHistory { get; set; }

    public DbSet<Customers> Customers { get; set; }

}

}

